# Generated by Django 4.0.4 on 2022-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_square_footage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='num_ofbedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
