# Generated by Django 4.0.4 on 2022-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_listings_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
