# Generated by Django 4.0.4 on 2022-05-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='num_bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
